### ISSUE TITLE
Norwegian date format is not correct

### ISSUE THREAD

**Issue by vimalraj-a** [telerik/kendo-intl#52] opened 2018-07-31 11:31 UTC
Norwegian short date is not same as kendo JS culture.

Kendo JS Culture (nb):
```
patterns: {
    d: "dd.MM.yyyy",
    D: "d. MMMM yyyy",
    F: "d. MMMM yyyy HH:mm:ss",
    g: "dd.MM.yyyy HH:mm",
    G: "dd.MM.yyyy HH:mm:ss",
    m: "d. MMMM",
    M: "d. MMMM",
    s: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
    t: "HH:mm",
    T: "HH:mm:ss",
    u: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'",
    y: "MMMM yyyy",
    Y: "MMMM yyyy"
}
```

Kendo-intl (nb):
```
patterns: {
    d: "d.M.y",
    D: "EEEE d. MMMM y",
    m: "d. MMM",
    M: "d. MMMM",
    y: "MMM y",
    Y: "MMMM y",
    F: "EEEE d. MMMM y HH:mm:ss",
    g: "d.M.y HH:mm",
    G: "d.M.y HH:mm:ss",
    t: "HH:mm",
    T: "HH:mm:ss",
    s: "yyyy'-'MM'-'dd'T'HH':'mm':'ss",
    u: "yyyy'-'MM'-'dd HH':'mm':'ss'Z'"
}
```

DD.MM.YYYY (e.g., 24.12.2006 for Christmas Eve, or 01.05.2006 for Labour Day) is by far the most common system, and is the one recommended by the Language Council of Norway. Dots are the most common separator, although you still see stroke and hyphen (especially in handwriting): 24/12-2005.
Refer: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Norway

**Comment by timlestander** [comment] 2018-09-13 11:12
I agree! The same thing goes for Sweden.

**Comment by tsvetomir** [comment] 2018-09-18 06:49
@vimalraj-a The CLDR database lists "dd.MM.y" as a [short date format](https://www.unicode.org/cldr/charts/34/summary/nb.html#1962) for Norwegian Bokmål. This format is very similar to what you expect, but years won't be padded to four digits.

The problem seems to be caused by [the date pattern definition](https://github.com/telerik/kendo-intl/blob/develop/src/cldr/load-dates.js#L8) which looks up [availableFormats](http://www.unicode.org/reports/tr35/tr35-dates.html#availableFormats_appendItems) instead of taking the short date format directly. /cc @danielkaradachki

@timlestander the [short date format](https://www.unicode.org/cldr/charts/34/summary/sv.html#1967) for Swedish is "dd-MM-y". Due to the same issue, we're picking up "y-MM-dd" instead. Do you think "dd-MM-y" is a better fit?

Reference the [Date Field Symbol Table](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) for interpreting the date formats.

**Comment by tsvetomir** [comment] 2018-09-25 07:07
@vimalraj-a Thanks for the input, we'll try to figure out the best option to apply this change.

Meanwhile we'll introduce support for [format objects](https://github.com/telerik/kendo-intl/blob/develop/docs/date-formatting/index.md#standard) for the Grid columns to address similar scenarios, e.g. `format="{ date: 'short' }".

**Comment by tsvetomir** [comment] 2018-09-27 14:08
The latest [development version](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the Grid supports format objects - feel free to give it a try.

**Comment by tsvetomir** [comment] 2019-02-22 08:30
The latest version of `@progress/kendo-angular-intl` allows patching the locale data for edge cases like this one. See [Modifying the Locale Data](https://www.telerik.com/kendo-angular-ui/components/globalization/internationalization/loading-data/#toc-modifying-the-locale-data). 

Closing this issue as changes to the default behavior might break other locales.

**Closed** 2019-02-22 08:30 UTC
Labels: bug, wontfix
